language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "netodevel-github"
    token:
      secure: "e7377abd32ab188e5cd6b13f9e0fc3749d53fcb7"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      
